name: PublishImage

on:
  release:
    types: [published]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    name: Publish docker image
    steps:
    - uses: actions/checkout@v2.2.0
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: justteddy/tmdbbot
        tag_with_ref: true
